Remove docs generation
uport-project/daf pull request #279
Opened 2020-11-24 14:36 UTC by jasonhealy

2020-11-24 14:48 UTC, simonas-notcat requested changes

2020-11-24 14:48 UTC, simonas-notcat commented on package.json
> -    "build": "yarn lerna run build && yarn extract-api && yarn generate-plugin-schema && yarn docs:api && yarn docs:examples && yarn docs:clean-temp && yarn prettier:examples",
@jasonhealy why did you remove `yarn extract-api` and `yarn docs:examples`?
These are needed to extract inline doc examples and include them into our integration tests

2020-11-25 07:01 UTC, mirceanis approved these changes
Looks good

2020-11-25 09:15 UTC, simonas-notcat approved these changes

2020-11-25 09:15 UTC, merged